runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth1=depth1" >>$GITHUB_OUTPUT
      echo "depth1=depth1" >>$GITHUB_ENV
  - uses: redgarb/local-post-steps-bug/.github/workflows/actions/depth2-absolut@master
    id: depth2
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth1 -> ${{ steps.output-value.outputs.depth1 }}"
      echo "Should be depth1 -> ${{ env.depth1 }}"
      echo "Should be depth2 -> ${{ steps.depth2.outputs.depth2 }}"
      echo "Should be depth2 -> ${{ env.depth2 }}"
      echo "Should be depth3 -> ${{ steps.depth2.outputs.depth3 }}"
      echo "Should be depth3 -> ${{ env.depth3 }}"
      echo "Should be depth4 -> ${{ steps.depth2.outputs.depth4 }}"
      echo "Should be depth4 -> ${{ env.depth4 }}"
  - uses: redgarb/local-post-steps-bug/.github/workflows/actions/post-step@master
    with:
      STEPS: ${{ tojson(steps) }}
