runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth4=depth4" >>$GITHUB_OUTPUT
      echo "depth4=depth4" >>$GITHUB_ENV
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth4 -> ${{ steps.output-value.outputs.depth4 }}"
      echo "Should be depth4 -> ${{ env.depth4 }}"
  - uses: redgarb/local-post-steps-bug/.github/workflows/actions/post-step@master
    with:
      STEPS: ${{ tojson(steps) }}
